# Generated by Django 4.0.1 on 2023-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=100)),
                ('runtimeMinutes', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('primaryName', models.CharField(max_length=100)),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField()),
            ],
        ),
    ]
