# Generated by Django 4.0.1 on 2023-02-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appnetfloox', '0004_rename_prediction_data_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
